//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWNewEgg.API.View.Resources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TWNewegg.API.View.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帳戶設定.
        /// </summary>
        public static string AccountSettings {
            get {
                return ResourceManager.GetString("AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商業報表.
        /// </summary>
        public static string BusinessReport {
            get {
                return ResourceManager.GetString("BusinessReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品圖文內容規範.
        /// </summary>
        public static string ContentPolicy {
            get {
                return ResourceManager.GetString("ContentPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 星期三，2013年10月9日.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幫助.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品建立.
        /// </summary>
        public static string ItemCreation {
            get {
                return ResourceManager.GetString("ItemCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品清單.
        /// </summary>
        public static string ItemList {
            get {
                return ResourceManager.GetString("ItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 語言.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登出.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商家帳戶管理.
        /// </summary>
        public static string ManageAccount {
            get {
                return ResourceManager.GetString("ManageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品管理.
        /// </summary>
        public static string ManageItems {
            get {
                return ResourceManager.GetString("ManageItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 訂單管理.
        /// </summary>
        public static string ManageOrder {
            get {
                return ResourceManager.GetString("ManageOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製造商.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 訊息.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顧客訂購清單.
        /// </summary>
        public static string OrderList {
            get {
                return ResourceManager.GetString("OrderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商家所得結算報表.
        /// </summary>
        public static string PaymentReport {
            get {
                return ResourceManager.GetString("PaymentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 政策 &amp; 合約.
        /// </summary>
        public static string PolicyAgreement {
            get {
                return ResourceManager.GetString("PolicyAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 隱私權政策.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 訂單退換貨清單.
        /// </summary>
        public static string ReturnList {
            get {
                return ResourceManager.GetString("ReturnList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商家邀請設定.
        /// </summary>
        public static string SellerInvitation {
            get {
                return ResourceManager.GetString("SellerInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商家維護與管理.
        /// </summary>
        public static string SellerManage {
            get {
                return ResourceManager.GetString("SellerManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商家關係維護與管理.
        /// </summary>
        public static string SellerRelationshipManage {
            get {
                return ResourceManager.GetString("SellerRelationshipManage", resourceCulture);
            }
        }
    }
}
