using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.WebPages.Html;

namespace TWNewEgg.DB.TWBACKENDDB.Models.ExtModels
{
    public class ReturnDetail
    {
        public string product_sellerproductid { get; set; }
        public string payType { get; set; }
        public string onreturndateNote { get; set; }
        public string cancelreturndateNote { get; set; }
        public string abnreturndateNote { get; set; }
        public string finreturndateNote { get; set; }
        public string OtherUpDataNote { get; set; }
        //public string refund2c_onreturndateNote { get; set; }
        //public string refund2c_cancelreturndateNote { get; set; }
        //public string refund2c_abnreturndateNote { get; set; }
        //public string refund2c_finreturndateNote { get; set; }
        public string item_delvtype { get; set; }

        public int Refund2c_ID { get; set; }
        public string Refund2c_Code { get; set; }
        public DateTime? Refund2c_Date { get; set; }
        public string Refund2c_ReFund2cUser { get; set; }
        public DateTime? Refund2c_PayDate { get; set; }
        public int? Refund2c_PostAge { get; set; }
        public int? Refund2c_Amount { get; set; }
        public int? Refund2c_AmountNOTax { get; set; }
        public int? Refund2c_Amountreal { get; set; }
        public DateTime? Refund2c_FinalDate { get; set; }
        public int? Refund2c_Status { get; set; }
        public int? Refund2c_Cause { get; set; }
        public int? Refund2c_RefundType { get; set; }
        public string Refund2c_BankID { get; set; }
        public string Refund2c_BankName { get; set; }
        public string Refund2c_SubBankName { get; set; }
        public string Refund2c_AccountNO { get; set; }
        public string Refund2c_AccountName { get; set; }
        public string Refund2c_CauseNote { get; set; }
        public DateTime? Refund2c_InvoiceConfirm { get; set; }
        public string Refund2c_ConfirmUser { get; set; }
        public DateTime? Refund2c_ConfirmDate { get; set; }
        public string Refund2c_ApplyUser { get; set; }
        public DateTime? Refund2c_ApplyDate { get; set; }
        public DateTime? Refund2c_PreFundDate { get; set; }
        public DateTime? Refund2c_ApproveDate { get; set; }
        public string Refund2c_MailNote { get; set; }
        public string Refund2c_ProcessID { get; set; }
        public int? Refund2c_RetgoodID { get; set; }
        public string Refund2c_ApproveUser { get; set; }
        public int? Refund2c_InvoiceResult { get; set; }
        public string Refund2c_RecvUser { get; set; }
        public DateTime? Refund2c_DiscountDate { get; set; }
        public string Refund2c_DiscountUser { get; set; }
        public string Refund2c_Finisher { get; set; }
        public string Refund2c_InvoiceNO { get; set; }
        public DateTime? Refund2c_InvoiceDate { get; set; }
        public int? Refund2c_InvoicePrice { get; set; }
        public DateTime? Refund2c_Refunding { get; set; }
        public int? Refund2c_FailCause { get; set; }
        public string Refund2c_Refund2cFile { get; set; }
        public int? Refund2c_ADJPrice { get; set; }
        public DateTime? Refund2c_StatusDate { get; set; }
        public DateTime? Refund2c_CreateDate { get; set; }
        public int? Refund2c_Updated { get; set; }
        public DateTime? Refund2c_UpdateDate { get; set; }
        public string Refund2c_UpdateUser { get; set; }
        public string Refund2c_Note { get; set; }
        public string Refund2c_UpdateNote { get; set; }
        public DateTime? Refund2c_OnRefundDate { get; set; }
        //public DateTime? refund2c_finreturndate { get; set; }
        public DateTime? Refund2c_AbnRefundDate { get; set; }
        public DateTime? Refund2c_CancelRefundDate { get; set; }
        public string Refund2c_ABNRefundReason { get; set; }

        public int Retgood_ID { get; set; }
        public string Retgood_Code { get; set; }
        public Nullable<int> Retgood_SupplierID { get; set; }
        public Nullable<int> Retgood_ProductID { get; set; }
        public Nullable<int> Retgood_CreatedFRM { get; set; }
        public Nullable<int> Retgood_RetgoodType { get; set; }
        public Nullable<System.DateTime> Retgood_Date { get; set; }
        public string Retgood_RetgoodUser { get; set; }
        public Nullable<System.DateTime> Retgood_FinalDate { get; set; }
        public Nullable<int> Retgood_Status { get; set; }
        public Nullable<decimal> Retgood_Price { get; set; }
        public Nullable<int> Retgood_Qty { get; set; }
        public Nullable<System.DateTime> Retgood_RECVGoodDate { get; set; }
        public Nullable<System.DateTime> Retgood_RecvinvoDate { get; set; }
        public Nullable<int> Retgood_InvocFmrslt { get; set; }
        public Nullable<System.DateTime> Retgood_InvocFMDate { get; set; }
        public string Retgood_InvocFMUser { get; set; }
        public string Retgood_UpdateUser { get; set; }
        public Nullable<int> Retgood_Cause { get; set; }
        public string Retgood_CauseNote { get; set; }
        public Nullable<int> Retgood_DealWith { get; set; }
        public Nullable<System.DateTime> Retgood_DealFinaldate { get; set; }
        public Nullable<int> Retgood_CheckinItemID { get; set; }
        public Nullable<int> Retgood_StockOutItemID { get; set; }
        public Nullable<int> Retgood_Target { get; set; }
        public string Retgood_DealNote { get; set; }
        public Nullable<int> Retgood_PostAge { get; set; }
        public string Retgood_BankName { get; set; }
        public string Retgood_BankBranch { get; set; }
        public string Retgood_AccountNO { get; set; }
        public string Retgood_AccountName { get; set; }
        public string Retgood_ProcessID { get; set; }
        public Nullable<int> Retgood_AmntRefund2c { get; set; }
        public string Retgood_OutFileName { get; set; }
        public string Retgood_ATTS { get; set; }
        public string Retgood_FrmName { get; set; }
        public string Retgood_FrmLocation { get; set; }
        public string Retgood_FrmZipcode { get; set; }
        public string Retgood_FrmADDR { get; set; }
        public string Retgood_FrmPhone { get; set; }
        public string Retgood_FrmPhone2 { get; set; }
        public string Retgood_FrmMobile { get; set; }
        public string Retgood_FrmEmail { get; set; }
        public Nullable<int> Retgood_FrmTime { get; set; }
        public string Retgood_FrmNote { get; set; }
        public string Retgood_ToCompany { get; set; }
        public string Retgood_ToName { get; set; }
        public string Retgood_ToLocation { get; set; }
        public string Retgood_ToZipcode { get; set; }
        public string Retgood_ToADDR { get; set; }
        public string Retgood_ToPhone { get; set; }
        public Nullable<int> Retgood_ScmenaBled { get; set; }
        public string Retgood_ScmNote { get; set; }
        public string Retgood_ShpCode { get; set; }
        public string Retgood_ShpEXPFile { get; set; }
        public Nullable<System.DateTime> Retgood_StckDate { get; set; }
        public string Retgood_StckUser { get; set; }
        public Nullable<System.DateTime> Retgood_EraseDate { get; set; }
        public Nullable<int> Retgood_EraseCause { get; set; }
        public string Retgood_EraseCauseNote { get; set; }
        public Nullable<System.DateTime> Retgood_SysDate { get; set; }
        public Nullable<int> Retgood_Updated { get; set; }
        public Nullable<System.DateTime> Retgood_UpdatedDate { get; set; }
        public string Retgood_UpdatedUser { get; set; }
        public DateTime? Retgood_OnReturnDate { get; set; }
        public DateTime? Retgood_FinReturnDate { get; set; }
        public DateTime? Retgood_ABNReturndate { get; set; }
        public DateTime? Retgood_CancelReturnDate { get; set; }
        public string Retgood_Note { get; set; }
        public string Retgood_UpdateNote { get; set; }
        public Nullable<int> Retgood_Declined { get; set; }
        public Nullable<decimal> Retgood_FreightalLocation { get; set; }
        public Nullable<decimal> Retgood_REShipping { get; set; }
        public Nullable<decimal> Retgood_TaxCost { get; set; }
        public Nullable<int> Retgood_ASNNumber { get; set; }
        public string Retgood_SendStatus { get; set; }
        public Nullable<System.DateTime> Retgood_SendDate { get; set; }
        public Nullable<int> Retgood_InventoryStatus { get; set; }
        public Nullable<DateTime> Retgood_InventoryStatusDate { get; set; }
        public string Retgood_InventoryStatusUser { get; set; }
        public Nullable<int> Retgood_ProductStatus { get; set; }
        public string Retgood_ABNReturnReason { get; set; }

        public string Process_ID { get; set; }
        public string Process_CartID { get; set; }
        public Nullable<int> Process_ProductID { get; set; }
        public Nullable<int> Process_ProductlistID { get; set; }
        public Nullable<int> Process_StoreID { get; set; }
        public string Process_ACTID { get; set; }
        public Nullable<int> Process_ActtkOut { get; set; }
        public Nullable<int> Process_ItemlistID { get; set; }
        public string Process_OrderItemCode { get; set; }
        public Nullable<int> Process_DealType { get; set; }
        public Nullable<int> Process_DealID { get; set; }
        public string Process_Title { get; set; }
        public string Process_Attribs { get; set; }
        public Nullable<decimal> Process_Price { get; set; }
        public Nullable<decimal> Process_Priceinst { get; set; }
        public Nullable<decimal> Process_Pricecoupon { get; set; }
        public Nullable<int> Process_RedmtkOut { get; set; }
        public Nullable<int> Process_RedmBLN { get; set; }
        public Nullable<int> Process_Redmfdbck { get; set; }
        public Nullable<int> Process_WftkOut { get; set; }
        public Nullable<int> Process_WfBLN { get; set; }
        public Nullable<int> Process_TaxType { get; set; }
        public Nullable<decimal> Process_Cost { get; set; }
        public Nullable<int> Process_Qty { get; set; }
        public string Process_InvoTitle { get; set; }
        public string Process_InvoTitleUser { get; set; }
        public Nullable<int> Process_Status { get; set; }
        public string Process_StatusNote { get; set; }
        public Nullable<System.DateTime> Process_Date { get; set; }
        public Nullable<System.DateTime> Process_CreateDate { get; set; }
        public Nullable<int> Process_STDELVCount { get; set; }
        public Nullable<System.DateTime> Process_STDSTExportDate { get; set; }
        public Nullable<System.DateTime> Process_StarvlDate { get; set; }
        public Nullable<System.DateTime> Process_StarvDateReal { get; set; }
        public Nullable<System.DateTime> Process_STCFMDate { get; set; }
        public Nullable<System.DateTime> Process_STKYCLRDate { get; set; }
        public Nullable<System.DateTime> Process_STSPCLRDate { get; set; }
        public Nullable<System.DateTime> Process_ProcOrder { get; set; }
        public Nullable<System.DateTime> Process_ProcIn { get; set; }
        public Nullable<System.DateTime> Process_WillShipping { get; set; }
        public Nullable<System.DateTime> Process_ProcOut { get; set; }
        public Nullable<System.DateTime> Process_Received { get; set; }
        public string Process_OrderNote { get; set; }
        public string Process_InNote { get; set; }
        public string Process_OutNote { get; set; }
        public string Process_ReceivedNote { get; set; }
        public Nullable<int> Process_SPID { get; set; }
        public string Process_SPNO { get; set; }
        public Nullable<int> Process_ShipperID { get; set; }
        public Nullable<int> Process_ADJPrice { get; set; }
        public Nullable<int> Process_Priveinst { get; set; }
        public Nullable<System.DateTime> Process_ApplySheet { get; set; }
        public string Process_ApplySheetNote { get; set; }
        public Nullable<int> Process_PurhItemID { get; set; }
        public Nullable<int> Process_CheckInItemID { get; set; }
        public Nullable<int> Process_RetgoodID { get; set; }
        public Nullable<int> Process_Refund2cID { get; set; }
        public Nullable<int> Process_DeliveryCheck { get; set; }
        public string Process_PROCUser { get; set; }
        public Nullable<int> Process_Parent { get; set; }
        public Nullable<int> Process_ScmenaBled { get; set; }
        public Nullable<int> Process_QtyProccncl { get; set; }
        public Nullable<int> Process_QtyPurh { get; set; }
        public Nullable<int> Process_QtySPOut { get; set; }
        public Nullable<int> Process_QtyCheckIn { get; set; }
        public Nullable<int> Process_QtyStckresv { get; set; }
        public Nullable<int> Process_Qtypkt { get; set; }
        public Nullable<int> Process_QtyDelivery { get; set; }
        public Nullable<int> Process_QtyRETGood { get; set; }
        public Nullable<int> Process_QtyCHGood { get; set; }
        public Nullable<int> Process_AmutRefund2c { get; set; }
        public Nullable<System.DateTime> Process_WorkHource { get; set; }
        public Nullable<System.DateTime> Process_StatusDate { get; set; }
        public string Process_DelivNO { get; set; }
        public Nullable<int> Process_Updated { get; set; }
        public string Process_UpdateUser { get; set; }
        public Nullable<System.DateTime> Process_UpdateDate { get; set; }
        public string Process_SN { get; set; }
        public decimal? Process_ShippingExpense { get; set; }
        public Nullable<int> Process_UpdateSapStatus { get; set; }
        public string Process_DOCNumber { get; set; }

        public string Cart_ID { get; set; }
        public string Cart_UserID { get; set; }
        public string Cart_IDNo { get; set; }
        public Nullable<decimal> Cart_Price { get; set; }
        public Nullable<int> Cart_Qty { get; set; }
        public string Cart_Zipcode { get; set; }
        public string Cart_ADDR { get; set; }
        public string Cart_Phone { get; set; }
        public string Cart_Phone2 { get; set; }
        public string Cart_Mobile { get; set; }
        public string Cart_Email { get; set; }
        public string Cart_Receiver { get; set; }
        public string Cart_IinvoiceTitle { get; set; }
        public string Cart_InvoiceNO { get; set; }
        public string Cart_Note { get; set; }
        public string Cart_CardType { get; set; }
        public string Cart_CardNO { get; set; }
        public string Cart_CardExpire { get; set; }
        public string Cart_CardHolder { get; set; }
        public Nullable<System.DateTime> Cart_Birthday { get; set; }
        public string Cart_CardADDR { get; set; }
        public string Cart_CardBank { get; set; }
        public string Cart_CardBankName { get; set; }
        public Nullable<int> Cart_StoreID { get; set; }
        public Nullable<int> Cart_PayType { get; set; }
        public string Cart_UsrIP { get; set; }
        public Nullable<System.DateTime> Cart_Date { get; set; }
        public string Cart_CardCheck { get; set; }
        public Nullable<int> Cart_Device { get; set; }
        public string Cart_CardPhone { get; set; }
        public string Cart_CardPhone2 { get; set; }
        public string Cart_CardMobile { get; set; }
        public Nullable<int> Cart_PaySelect { get; set; }
        public string Cart_Username { get; set; }
        public Nullable<int> Cart_ShipType { get; set; }
        public Nullable<int> Cart_ShipPrice { get; set; }
        public Nullable<int> Cart_Status { get; set; }
        public string Cart_Location { get; set; }
        public string Cart_CardLocation { get; set; }
        public string Cart_CardZipcode { get; set; }
        public string Cart_ServerName { get; set; }
        public string Cart_CoserverName { get; set; }
        public Nullable<int> Cart_HpType { get; set; }
        public string Cart_InvoLocation { get; set; }
        public string Cart_InvoZipcode { get; set; }
        public string Cart_InvoADDR { get; set; }
        public string Cart_InvoReceiver { get; set; }
        public string Cart_FrmCode { get; set; }
        public Nullable<int> Cart_UsrLOC { get; set; }
        public string Cart_UserZipcode { get; set; }
        public string Cart_UsrADDR { get; set; }
        public string Cart_CMPName { get; set; }
        public Nullable<int> Cart_CMPLOC { get; set; }
        public string Cart_CMOZipcode { get; set; }
        public string Cart_CMPADDR { get; set; }
        public string Cart_CntName { get; set; }
        public string Cart_CnRelation { get; set; }
        public string Cart_CntTelCMP { get; set; }
        public string Cart_CntTelHome { get; set; }
        public string Cart_CntMobile { get; set; }
        public string Cart_StID { get; set; }
        public string Cart_StName { get; set; }
        public string Cart_StPhone { get; set; }
        public string Cart_StADDR { get; set; }
        public Nullable<System.DateTime> Cart_StatusDate { get; set; }
        public Nullable<System.DateTime> Cart_CreateDate { get; set; }
        public Nullable<int> Cart_Updated { get; set; }
        public string Cart_UpdateUser { get; set; }
        public Nullable<System.DateTime> Cart_UpdateDate { get; set; }
        public string Cart_TelDay { get; set; }
        public string Cart_TelNight { get; set; }
        public string Cart_RecvMobile { get; set; }
        public string Cart_DelivData { get; set; }
        public string Cart_DelivHitNote { get; set; }
        public Nullable<System.DateTime> Cart_AuthDate { get; set; }
        public string Cart_AuthCode { get; set; }
        public string Cart_AuthNote { get; set; }
        public string Cart_ActCode { get; set; }
        public string Cart_StatusNote { get; set; }
        public Nullable<int> Cart_SalesorderGroupID { get; set; }
        public string Cart_RecvENGName { get; set; }
        public string Cart_DelivENGADDR { get; set; }
        public string Cart_DelivNO { get; set; }
        public int? Cart_DelvStatus { get; set; }
        public Nullable<System.DateTime> Cart_DelvStatusDate { get; set; }
        public int? Cart_RefSONumber { get; set; }
        public int? Cart_Forwarder { get; set; }
        public int? Cart_InventoryStatus { get; set; }
        public DateTime? Cart_InventoryStatusDate { get; set; }
        public string Cart_IinventorystatusUser { get; set; }

        public List<SelectListItem> statusList { get; set; }

    }
}