//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWNewEgg.ECWeb.Resources.PageMgmt {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageMgmtResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageMgmtResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TWNewEgg.ECWeb.Resources.PageMgmt.PageMgmtResource", typeof(PageMgmtResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上线.
        /// </summary>
        public static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要上线此页面.
        /// </summary>
        public static string ActiveConfirm {
            get {
                return ResourceManager.GetString("ActiveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要取消编辑.
        /// </summary>
        public static string CancelConfirm {
            get {
                return ResourceManager.GetString("CancelConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择档案.
        /// </summary>
        public static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空.
        /// </summary>
        public static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要清空此页面.
        /// </summary>
        public static string CleanConfirm {
            get {
                return ResourceManager.GetString("CleanConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内容.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资料物件 .
        /// </summary>
        public static string CustomObject {
            get {
                return ResourceManager.GetString("CustomObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下线.
        /// </summary>
        public static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要删除此页面.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除页面.
        /// </summary>
        public static string DeletePage {
            get {
                return ResourceManager.GetString("DeletePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动态物件.
        /// </summary>
        public static string DynamicObject {
            get {
                return ResourceManager.GetString("DynamicObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑中.
        /// </summary>
        public static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑物件.
        /// </summary>
        public static string EditObject {
            get {
                return ResourceManager.GetString("EditObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片物件.
        /// </summary>
        public static string ImageObject {
            get {
                return ResourceManager.GetString("ImageObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图.
        /// </summary>
        public static string Img {
            get {
                return ResourceManager.GetString("Img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片连结.
        /// </summary>
        public static string ImgLink {
            get {
                return ResourceManager.GetString("ImgLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无.
        /// </summary>
        public static string imgN {
            get {
                return ResourceManager.GetString("imgN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 轮播.
        /// </summary>
        public static string imgR {
            get {
                return ResourceManager.GetString("imgR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 翻转显示内容.
        /// </summary>
        public static string imgT {
            get {
                return ResourceManager.GetString("imgT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 轮播速度（秒）.
        /// </summary>
        public static string ImgTurnSpeed {
            get {
                return ResourceManager.GetString("ImgTurnSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片上传.
        /// </summary>
        public static string ImgUpload {
            get {
                return ResourceManager.GetString("ImgUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 圖片網址.
        /// </summary>
        public static string ImgUrl {
            get {
                return ResourceManager.GetString("ImgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连结目标.
        /// </summary>
        public static string LinkTarget {
            get {
                return ResourceManager.GetString("LinkTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面连结.
        /// </summary>
        public static string PageUrl {
            get {
                return ResourceManager.GetString("PageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退回.
        /// </summary>
        public static string R {
            get {
                return ResourceManager.GetString("R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回复.
        /// </summary>
        public static string Recover {
            get {
                return ResourceManager.GetString("Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要回到前一次上线状态.
        /// </summary>
        public static string RecoverConfirm {
            get {
                return ResourceManager.GetString("RecoverConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要退回此页面.
        /// </summary>
        public static string RejectConfirm {
            get {
                return ResourceManager.GetString("RejectConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 储存.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要储存此页面.
        /// </summary>
        public static string SaveConfirm {
            get {
                return ResourceManager.GetString("SaveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新页.
        /// </summary>
        public static string TargetBlank {
            get {
                return ResourceManager.GetString("TargetBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本页 .
        /// </summary>
        public static string TargetSelf {
            get {
                return ResourceManager.GetString("TargetSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字物件.
        /// </summary>
        public static string TextObject {
            get {
                return ResourceManager.GetString("TextObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标题.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 视频物件.
        /// </summary>
        public static string VideoObject {
            get {
                return ResourceManager.GetString("VideoObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 待审核.
        /// </summary>
        public static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 送审.
        /// </summary>
        public static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要送审此页面.
        /// </summary>
        public static string WaitConfirm {
            get {
                return ResourceManager.GetString("WaitConfirm", resourceCulture);
            }
        }
    }
}
