//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWNewEgg.ECWeb.Resources.PageMgmt {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TWNewEgg.ECWeb.Resources.PageMgmt.PropertyResource", typeof(PropertyResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动对齐.
        /// </summary>
        public static string AutoAlign {
            get {
                return ResourceManager.GetString("AutoAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 色码.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片.
        /// </summary>
        public static string BackgroundImage {
            get {
                return ResourceManager.GetString("BackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他.
        /// </summary>
        public static string BackgroundOther {
            get {
                return ResourceManager.GetString("BackgroundOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 元件属性.
        /// </summary>
        public static string ComponentProperty {
            get {
                return ResourceManager.GetString("ComponentProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控制.
        /// </summary>
        public static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 锁定物件位置.
        /// </summary>
        public static string Draggable {
            get {
                return ResourceManager.GetString("Draggable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 固定长宽.
        /// </summary>
        public static string FixedRatio {
            get {
                return ResourceManager.GetString("FixedRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从相簿.
        /// </summary>
        public static string FromAlbum {
            get {
                return ResourceManager.GetString("FromAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网页背景.
        /// </summary>
        public static string PageBackground {
            get {
                return ResourceManager.GetString("PageBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名.
        /// </summary>
        public static string PageName {
            get {
                return ResourceManager.GetString("PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网页属性.
        /// </summary>
        public static string PageProperty {
            get {
                return ResourceManager.GetString("PageProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传图片.
        /// </summary>
        public static string UploadImg {
            get {
                return ResourceManager.GetString("UploadImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 宽.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深.
        /// </summary>
        public static string ZIndex {
            get {
                return ResourceManager.GetString("ZIndex", resourceCulture);
            }
        }
    }
}
