// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TWNewEgg.SMSService.Models
{
    /// <summary>
    /// 中華電信SMS簡訊資料模型
    /// </summary>
    public class HinetSMSSubmitModel
    {
        private string _account = string.Empty;
        private string _password = string.Empty;
        private FromAddrTypeEnum _from_addr_type;
        private string _from_addr;
        private ToAddrTypeEnum _to_addr_type;
        private string _to_addr;
        private string _msg_dlv_time;
        private string _msg_expire_time;
        private MsgTypeEnum _msg_type;
        private string _msg_dcs;
        private string _msg_pclid;
        private string _msg_udhi;
        private string _msg;
        private string _dest_port;

        /// <summary>
        /// http網址
        /// </summary>
        public string httpurl
        {
            get
            {
                return "http://imsp.emome.net:8008/imsp/sms/servlet/SubmitSM";
            }
        }

        /// <summary>
        /// https網址
        /// </summary>
        public string httpsurl
        {
            get
            {
                return "https://imsp.emome.net:4443/imsp/sms/servlet/SubmitSM";
            }
        }

        /// <summary>
        /// 帳號
        /// </summary>
        public string account 
        {
            get
            {
                return _account;
            }

            set
            {
                _account = value;
            }
        }

        /// <summary>
        /// 密碼
        /// </summary>
        public string password
        {
            get
            {
                return _password;
            }

            set
            {
                _password = value;
            }
        }

        /// <summary>
        /// 發送者號碼的種類
        /// (發訊號碼須為09開頭)
        /// </summary>
        public FromAddrTypeEnum from_addr_type
        {
            get
            {
                return _from_addr_type;
            }

            set
            {
                _from_addr_type = value;
            }
        }

        /// <summary>
        /// SMS訊息的發送者的號碼
        /// </summary>
        public string from_addr
        {
            get
            {
                return _from_addr;
            }

            set
            {
                _from_addr = value;
            }
        }

        /// <summary>
        /// 發送對象號碼的種類
        /// </summary>
        public ToAddrTypeEnum to_addr_type
        {
            get
            {
                return _to_addr_type;
            }

            set
            {
                _to_addr_type = value;
            }
        }

        /// <summary>
        /// SMS訊息的發送對象的號碼
        /// 此欄可以包含一個以上的門號，以ASCII的逗號 (,) 隔開，最多接受20個獨立門號。
        /// </summary>
        public string to_addr
        {
            get
            {
                return _to_addr;
            }

            set
            {
                _to_addr = value;
            }
        }

        /// <summary>
        /// SMS訊息的預約傳送時間，時間格式為: yymmddHHMM
        /// 請注意預約時間不得超過48小時。
        /// 若不需要預約傳送功能, 此欄可不填。
        /// </summary>
        public string msg_dlv_time
        {
            get
            {
                return _msg_dlv_time;
            }

            set
            {
                _msg_dlv_time = value;
            }
        }

        /// <summary>
        /// SMS訊息的失效時間，以分鐘為單位。
        /// 若不需設定失效時間，則將此欄設為0，或是不填值。
        /// </summary>
        public string msg_expire_time
        {
            get
            {
                return _msg_expire_time;
            }

            set
            {
                _msg_expire_time = value;
            }
        }

        /// <summary>
        /// SMS訊息的訊息種類
        /// </summary>
        public MsgTypeEnum msg_type
        {
            get
            {
                return _msg_type;
            }

            set
            {
                _msg_type = value;
            }
        }

        /// <summary>
        /// SMS訊息的訊息編碼方式
        /// SMS訊息純粹為文字訊息(中文或英文)的話，可以用default value=0送出
        /// 若是binary data的話，請自行填入正確的編碼值
        /// </summary>
        public string msg_dcs
        {
            get
            {
                return _msg_dcs;
            }

            set
            {
                _msg_dcs = value;
            }
        }

        /// <summary>
        /// SMS訊息的訊息GSM協定識別碼，通常設為0，若有需要可自行設定所需之數值。
        /// </summary>
        public string msg_pclid
        {
            get
            {
                return _msg_pclid;
            }

            set
            {
                _msg_pclid = value;
            }
        }

        /// <summary>
        /// 若需設UDHI，此欄設為1，反之，此欄設為0。
        /// </summary>
        public string msg_udhi
        {
            get
            {
                return _msg_udhi;
            }

            set
            {
                _msg_udhi = value;
            }
        }

        /// <summary>
        /// SMS訊息的訊息內容
        /// 若此通SMS訊息含有中文的話，請用Big5編碼送出 (適用於msg_type=0及1)
        /// 當msg_type=2時，文字請用Unicode-Big或UTF-16BE來編碼，並將內容以HEX來表示
        /// 當msg_type=3時，Binary的資料也須以Hex來表示
        /// 當msg_type=2或3時，msg長度限制為132 bytes，約66個中文字。
        /// </summary>
        public string msg
        {
            get
            {
                return _msg;
            }

            set
            {
                _msg = value;
            }
        }

        /// <summary>
        /// msg_type=2或3時, 訊息將送至手機上此參數所指定的port (msg_udhi將自動設為1)，
        /// 以HEX字串表示，如port = 1234，則dest_port=04D2。
        /// </summary>
        public string dest_port
        {
            get
            {
                return _dest_port;
            }

            set
            {
                _dest_port = value;
            }
        }
    }

    /// <summary>
    /// 發送者號碼 (from address) 的種類列舉
    /// </summary>
    public enum FromAddrTypeEnum
    {
        /// <summary>
        /// 手機門號(發訊號碼須為09開頭)
        /// </summary>
        MobileNumber = 0,
        /// <summary>
        /// emome代碼
        /// </summary>
        EmomeCode = 1,
        /// <summary>
        /// 帳號
        /// </summary>
        Account = 2
    }

    /// <summary>
    /// 發送對象號碼 (to address) 的種類列舉
    /// </summary>
    public enum ToAddrTypeEnum
    {
        /// <summary>
        /// 手機門號(發送對象為手機門號)
        /// </summary>
        MobileNumber = 0,
        /// <summary>
        /// emome代碼
        /// </summary>
        EmomeCode = 1
    }

    /// <summary>
    /// SMS訊息的訊息種類列舉
    /// </summary>
    public enum MsgTypeEnum
    {
        /// <summary>
        /// 一般通用簡訊
        /// </summary>
        General = 0,
        /// <summary>
        /// pop-up 簡訊
        /// </summary>
        Popup = 1,
        /// <summary>
        /// 傳送至手機上的應用程式，資料型態為文字
        /// </summary>
        AppString = 2,
        /// <summary>
        /// binary 型態
        /// </summary>
        Binary = 3
    }

}
